### PR TITLE
crossbrowser selector

### PR DESCRIPTION
**Pull request by msafronov**
"document.querySelector" is not supported by old browsers (IE8 and lower as example)

### CODE REVIEW

**Review by eddyerburgh — COMMENTED** [review]
Hey, thanks for quick PR! Have you tested on a browser without document.querySelector?

**Comment by kotoo** [comment]
hi ) nope, just watch it on http://caniuse.com/#search=querySelector%2FquerySelectorAll . i can install windows xp image on virtualbox with old IE version (in my fedora 25) for testing )

**Comment by eddyerburgh** [comment]
That would be good - I'm going to get [ci testling](https://ci.testling.com/guide/quick_start) setup to run the tests in ie 6+. 

I think some of the tests will fail with this PR on ie8. [This test](https://github.com/eddyerburgh/is-dom-selector/blob/master/test/isDomSelector.spec.js#L34), and the attribute tests aren't covered by the fallback.

Maybe a poly-fill would be better - http://stackoverflow.com/questions/28194786/how-to-make-document-queryselector-work-in-ie6

**Comment by kotoo** [comment]
that code from stackoverflow looks better ofcourse. the library should not change the global object, i just write a custom method.

**Comment by kotoo** [comment]
i see, you already write it, good job man! task is closed

**Pull request closed without merging**
